#
# Run Checks
#
name: Check

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  #
  # Run SonarQube scan
  #
  check-sonar-generic:
    uses: EdisonInternational/actions/.github/workflows/check-sonar-generic.yml@main
    with:
        #VERSION: 1.0.0          (optional, default=github.ref_name)
    secrets: inherit
