name: Check_DotNet

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-sonar-generic:
    uses: EdisonInternational/actions/.github/workflows/check-sonar-dotnet.yml@v1
    with:
      # Read from repository/org variables. Fallbacks shown as examples:
      PROJECT: ${{ vars.PROJECT_PATH || '.' }}
      DOTNET_VERSION: ${{ vars.DOTNET_VERSION || '8' }}
      # Save the SONAR_EXCLUSIONS as an action repository variable with a comma ',' between different paths
      SONAR_EXCLUSIONS: "\"${{ vars.SONAR_EXCLUSIONS || '' }}\""
    secrets: inherit
    permissions:
      contents: read
      actions: read
      checks: write
