name: Check XCode

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-sonar-generic:
    uses: EdisonInternational/actions/.github/workflows/check-sonar-maven.yml@main
    with:
      # Read from repository/org variables. Fallbacks shown as examples:
      PROJECT: ${{ vars.PROJECT_PATH || '.' }}
      SCHEME: ${{ vars.SCHEME }}
      DESTINATION: ${{ vars.DESTINATION || '' }}

    secrets: inherit
    permissions:
      contents: read
      actions: read
      checks: write
