#
# Run Checks
#
name: Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  #
  # Run SonarQube scan
  #
  check-sonar-generic:
    uses: EdisonInternational/actions/.github/workflows/check-sonar-generic.yml@main
    with:
      PROJECT: ${{ vars.PROJECT_PATH || '.' }}
      SONAR_EXCLUSIONS: ${{ SONAR_EXCLUSIONS || '' }}
    secrets: inherit
    permissions:
      contents: read
      actions: read
      checks: write
